In [4]:
import numpy as np
import pandas as pd
import sklearn as sk
import warnings
warnings.filterwarnings('ignore')

In [5]:
data = pd.read_csv("paddydataset.csv")
data

,Hectares,Agriblock,Variety,Soil Types,Seedrate(in Kg),LP_Mainfield(in Tonnes),Nursery,Nursery area (Cents),LP_nurseryarea(in Tonnes),DAP_20days,...,Wind Direction_D1_D30,Wind Direction_D31_D60,Wind Direction_D61_D90,Wind Direction_D91_D120,Relative Humidity_D1_D30,Relative Humidity_D31_D60,Relative Humidity_D61_D90,Relative Humidity_D91_D120,Trash(in bundles),Paddy yield(in Kg)
0,6,Cuddalore,CO_43,alluvial,150,75.0,dry,120,6,240,...,SW,W,NNW,WSW,72.0,78,88,85,540,35028
1,6,Kurinjipadi,ponmani,clay,150,75.0,wet,120,6,240,...,NW,S,SE,SSE,64.6,85,84,87,600,35412
2,6,Panruti,delux ponni,alluvial,150,75.0,dry,120,6,240,...,ENE,NE,NNE,W,85.0,96,84,79,600,36300
3,6,Kallakurichi,CO_43,clay,150,75.0,wet,120,6,240,...,W,WNW,SE,S,88.5,95,81,84,540,35016
4,6,Sankarapuram,ponmani,alluvial,150,75.0,dry,120,6,240,...,SSE,W,SW,NW,72.7,91,83,81,600,34044
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2784,1,Kallakurichi,CO_43,alluvial,25,12.5,wet,20,1,40,...,W,WNW,SE,S,88.5,95,81,84,90,5836
2785,1,Sankarapuram,ponmani,clay,25,12.5,wet,20,1,40,...,SSE,W,SW,NW,72.7,91,83,81,100,5723
2786,1,Chinnasalem,delux ponni,clay,25,12.5,wet,20,1,40,...,E,ENE,NE,NNW,78.6,80,92,88,80,5723
2787,1,Cuddalore,CO_43,alluvial,25,12.5,wet,20,1,40,...,SW,W,NNW,WSW,72.0,78,88,85,90,5916
2788,1,Kurinjipadi,delux ponni,clay,25,12.5,wet,20,1,40,...,NW,S,SE,SSE,64.6,85,84,87,80,5873

In [6]:
data.duplicated().value_counts()

False    2338
True      451
Name: count, dtype: int64

In [7]:
data.drop_duplicates(inplace=True)

In [8]:
data.value_counts()

Hectares   Agriblock     Variety  Soil Types  Seedrate(in Kg)  LP_Mainfield(in Tonnes)  Nursery  Nursery area (Cents)  LP_nurseryarea(in Tonnes)  DAP_20days  Weed28D_thiobencarb  Urea_40Days  Potassh_50Days  Micronutrients_70Days  Pest_60Day(in ml)  30DRain( in mm)  30DAI(in mm)  30_50DRain( in mm)  30_50DAI(in mm)  51_70DRain(in mm)  51_70AI(in mm)  71_105DRain(in mm)  71_105DAI(in mm)  Min temp_D1_D30  Max temp_D1_D30  Min temp_D31_D60  Max temp_D31_D60  Min temp_D61_D90  Max temp_D61_D90  Min temp_D91_D120  Max temp_D91_D120  Inst Wind Speed_D1_D30(in Knots)  Inst Wind Speed_D31_D60(in Knots)  Inst Wind Speed_D61_D90(in Knots)  Inst Wind Speed_D91_D120(in Knots)  Wind Direction_D1_D30  Wind Direction_D31_D60  Wind Direction_D61_D90  Wind Direction_D91_D120  Relative Humidity_D1_D30  Relative Humidity_D31_D60  Relative Humidity_D61_D90  Relative Humidity_D91_D120  Trash(in bundles)  Paddy yield(in Kg)
6          Sankarapuram  ponmani  clay        150              75.0                     wet      120                   6                          240         12                   162.78       62.28           90                     3600               18.1             21.9          185.6               272.4            166.1              250.9           60.2                64.8              20.5             32               17.5              28                18.0              34.0              16.5               35.0               10                                12                                 10                                 12                                  SSE                    W                       SW                      NW                       72.7                      91                         83                         81                          600                37242                 1
1          Chinnasalem   CO_43    alluvial    25               12.5                     dry      20                    1                          40          2                    27.13        10.38           15                     600                18.1             21.9          185.6               272.4            166.1              250.9           60.2                64.8              18.0             31               15.5              34                15.0              33.0              15.0               31.5               6                                 6                                  8                                  10                                  E                      ENE                     NE                      NNW                      78.6                      80                         92                         88                          90                 5836                  1
6          Sankarapuram  CO_43    clay        150              75.0                     dry      120                   6                          240         12                   162.78       62.28           90                     3600               18.1             21.9          185.6               272.4            166.1              250.9           60.2                64.8              20.5             32               17.5              28                18.0              34.0              16.5               35.0               10                                12                                 10                                 12                                  SSE                    W                       SW                      NW                       72.7                      91                         83                         81                          540                38586                 1
                                                                                        wet      120                   6                          240         12                   162.78       62.28           90                     3600               18.1             21.9          185.6               272.4            166.1              250.9           60.2                64.8              20.5             32               17.5              28                18.0              34.0              16.5               35.0               10                                12                                 10                                 12                                  SSE                    W                       SW                      NW                       72.7                      91                         83                         81                          540                37086                 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  37866                 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ..
1          Chinnasalem   CO_43    alluvial    25               12.5                     wet      20                    1                          40          2                    27.13        10.38           15                     600                18.1             21.9          185.6               272.4            166.1              250.9           60.2                64.8              18.0             31               15.5              34                15.0              33.0              15.0               31.5               6                                 6                                  8                                  10                                  E                      ENE                     NE                      NNW                      78.6                      80                         92                         88                          90                 5836                  1
                                  clay        25               12.5                     dry      20                    1                          40          2                    27.13        10.38           15                     600                18.1             21.9          185.6               272.4            166.1              250.9           60.2                64.8              18.0             31               15.5              34                15.0              33.0              15.0               31.5               6                                 6                                  8                                  10                                  E                      ENE                     NE                      NNW                      78.6                      80                         92                         88                          90                 5463                  1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  5723                  1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  5873                  1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  5908                  1
Name: count, Length: 2338, dtype: int64

In [9]:
data.shape

(2338, 45)

In [10]:
from sklearn.preprocessing import LabelEncoder
lab_enc = LabelEncoder()
for i in data.select_dtypes(include='object'):
    data[i] = lab_enc.fit_transform(data[i])

In [11]:
from sklearn.preprocessing import StandardScaler
st_scalar = StandardScaler()
scale_data = st_scalar.fit_transform(data)

In [12]:
from sklearn.decomposition import PCA
pca = PCA(n_components=5)
pca_df = pca.fit_transform(data)

In [13]:
pca_df

array([[ 1.24927760e+04,  1.99712944e+02, -1.92358856e+01,
        -9.40667831e+00,  3.48032232e+00],
       [ 1.28758955e+04,  1.77557495e+02,  4.23927066e+01,
        -1.17847605e+01, -5.84283686e+00],
       [ 1.37599195e+04,  9.39418977e+01,  4.96413273e+01,
         1.43452251e+01,  5.74532875e-01],
       ...,
       [-1.68567610e+04, -7.56559529e+01,  6.07520061e+00,
         1.28817256e+01,  3.09260557e+00],
       [-1.69691150e+04, -6.26992677e+01,  1.47991744e+01,
         1.60951871e+00, -8.74167048e+00],
       [-1.69693947e+04, -6.73477368e+01, -4.60371724e+00,
        -6.59838579e+00,  1.10101793e+01]], shape=(2338, 5))

In [ ]:
pd.DataFrame(pca_df)

                 0           1          2          3          4
0     12492.775972  199.712944 -19.235886  -9.406678   3.480322
1     12875.895483  177.557495  42.392707 -11.784761  -5.842837
2     13759.919464   93.941898  49.641327  14.345225   0.574533
3     12480.829378  200.834637 -19.256027  13.302329   3.181299
4     11514.020113  306.347559  30.939663   2.105007  -8.809535
...            ...         ...        ...        ...        ...
2333 -16819.786517  -76.808657  16.135302 -12.268738  -5.915518
2334 -17199.360650  -45.612915  -6.598361  13.846749   0.373558
2335 -16856.761042  -75.655953   6.075201  12.881726   3.092606
2336 -16969.114984  -62.699268  14.799174   1.609519  -8.741670
2337 -16969.394717  -67.347737  -4.603717  -6.598386  11.010179

[2338 rows x 5 columns]

In [16]:
print(pca.explained_variance_ratio_)

[9.99881222e-01 1.03855570e-04 1.27133981e-05 1.18538992e-06
 5.09064994e-07]